/* Lógico_1.brM3_V1: */

CREATE TABLE ESPECIALIDADE (
    cod_especialidade INTEGER,
    cod_medico INTEGER
);

CREATE TABLE CAD_ESPECIALIDADE (
    cod_especialidade INTEGER PRIMARY KEY,
    especialidade VARCHAR(60)
);

CREATE TABLE MEDICO (
    cod_medico INTEGER PRIMARY KEY,
    nome_medico VARCHAR(100),
    crm INTEGER,
    cod_estado INTEGER
);

CREATE TABLE HOSPITAL (
    cod_hospital INTEGER PRIMARY KEY,
    hospital VARCHAR(60)
);

ALTER TABLE HOSPITAL ADD COLUMN UF_HOSPITAL INTEGER;

CREATE TABLE TRATAMENTO (
    cod_tratamento INTEGER PRIMARY KEY,
    cod_paciente INTEGER,
    cod_medico INTEGER,
    cod_indisposicao INTEGER,
    ini_trat DATE,
    fim_trat DATE,
    cod_hospital INTEGER
);

CREATE TABLE PACIENTE (
    cod_paciente INTEGER PRIMARY KEY,
    nome_paciente VARCHAR(100),
    peso FLOAT,
    altura FLOAT,
    data_nascimento DATE,
    cpf BIGINT,
    cod_end INTEGER
);

/* ALTER TABLE PACIENTE ADD COLUMN SEXO VARCHAR(2); */

CREATE TABLE ENDERECO (
    cod_end INTEGER PRIMARY KEY,
    cod_rua INTEGER,
    cep INTEGER,
    num_complemento INTEGER,
    num_residencia INTEGER
);

CREATE TABLE ESTADO (
    cod_estado INTEGER PRIMARY KEY,
    estado VARCHAR(50)
);

CREATE TABLE CIDADE (
    cod_cidade INTEGER PRIMARY KEY,
    cidade VARCHAR(100),
    cod_estado INTEGER
);

CREATE TABLE BAIRRO (
    cod_bairro INTEGER PRIMARY KEY,
    bairro VARCHAR(100),
    cod_cidade INTEGER
);

CREATE TABLE INDISPOSICAO (
    indisposicao VARCHAR(100),
    cod_indisposicao INTEGER PRIMARY KEY
);

CREATE TABLE MEDICAMENTO (
    cod_tratamento INTEGER,
    cod_medicamento INTEGER
);

CREATE TABLE CAD_MEDICAMENTO (
    cod_medicamento INTEGER PRIMARY KEY,
    medicamento VARCHAR(100)
);

CREATE TABLE RUA (
    cod_bairro INTEGER,
    rua VARCHAR(100),
    cod_rua INTEGER PRIMARY KEY
);
 
ALTER TABLE ESPECIALIDADE ADD CONSTRAINT ESPECIALIDADE_COD_MEDICO_FKEY
    FOREIGN KEY (cod_medico)
    REFERENCES MEDICO (cod_medico) MATCH FULL
    ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ESPECIALIDADE ADD CONSTRAINT ESPECIALIDADE_COD_ESPECIALIDADE_FKEY
    FOREIGN KEY (cod_especialidade)
    REFERENCES ESPECIALIDADE (cod_especialidade) MATCH FULL
    ON UPDATE CASCADE ON DELETE CASCADE;
 
ALTER TABLE MEDICO ADD CONSTRAINT MEDICO_COD_ESTADO_FKEY
    FOREIGN KEY (cod_estado)
    REFERENCES ESTADO (cod_estado) MATCH FULL
    ON UPDATE CASCADE ON DELETE CASCADE;
 
ALTER TABLE HOSPITAL ADD CONSTRAINT HOSPITAL_UF_HOSPITAL_FKEY
    FOREIGN KEY (uf_hospital)
    REFERENCES ESTADO (cod_estado) MATCH FULL
    ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE TRATAMENTO ADD CONSTRAINT TRATAMENTO_COD_HOSPITAL_FKEY
    FOREIGN KEY (cod_hospital)
    REFERENCES HOSPITAL (cod_hospital) MATCH FULL
    ON UPDATE CASCADE ON DELETE CASCADE;
 
ALTER TABLE TRATAMENTO ADD CONSTRAINT TRATAMENTO_COD_INDISPOSICAO_FKEY
    FOREIGN KEY (cod_indisposicao)
    REFERENCES INDISPOSICAO (cod_indisposicao) MATCH FULL
    ON UPDATE CASCADE ON DELETE CASCADE;
 
ALTER TABLE TRATAMENTO ADD CONSTRAINT TRATAMENTO_COD_MEDICO_FKEY
    FOREIGN KEY (cod_medico)
    REFERENCES MEDICO (cod_medico) MATCH FULL
    ON UPDATE CASCADE ON DELETE CASCADE;
 
ALTER TABLE TRATAMENTO ADD CONSTRAINT TRATAMENTO_COD_PACIENTE_FKEY
    FOREIGN KEY (cod_paciente)
    REFERENCES PACIENTE (cod_paciente) MATCH FULL
    ON UPDATE CASCADE ON DELETE CASCADE;
 
ALTER TABLE PACIENTE ADD CONSTRAINT PACIENTE_COD_END_FKEY
    FOREIGN KEY (cod_end)
    REFERENCES ENDERECO (cod_end) MATCH FULL
    ON UPDATE CASCADE ON DELETE CASCADE;
 
ALTER TABLE ENDERECO ADD CONSTRAINT ENDERECO_COD_RUA_FKEY
    FOREIGN KEY (cod_rua)
    REFERENCES Rua (cod_rua) MATCH FULL
    ON UPDATE CASCADE ON DELETE CASCADE;
 
ALTER TABLE CIDADE ADD CONSTRAINT CIDADE_COD_ESTADO_FKEY
    FOREIGN KEY (cod_estado)
    REFERENCES ESTADO (cod_estado) MATCH FULL
    ON UPDATE CASCADE ON DELETE CASCADE;
 
ALTER TABLE BAIRRO ADD CONSTRAINT BAIRRO_COD_CIDADE_FKEY
    FOREIGN KEY (cod_cidade)
    REFERENCES CIDADE (cod_cidade) MATCH FULL
    ON UPDATE CASCADE ON DELETE CASCADE;
 
ALTER TABLE MEDICAMENTO ADD CONSTRAINT MEDICAMENTO_COD_TRATAMENTO_FKEY
    FOREIGN KEY (cod_tratamento)
    REFERENCES TRATAMENTO (cod_tratamento) MATCH FULL
    ON UPDATE CASCADE ON DELETE CASCADE;
 
ALTER TABLE MEDICAMENTO ADD CONSTRAINT MEDICAMENTO_COD_MEDICAMENTO_FKEY
    FOREIGN KEY (cod_medicamento)
    REFERENCES CAD_MEDICAMENTO (cod_medicamento) MATCH FULL
    ON UPDATE CASCADE ON DELETE CASCADE;
 
ALTER TABLE RUA ADD CONSTRAINT RUA_COD_BAIRRO_FKEY 
    FOREIGN KEY (cod_bairro)
    REFERENCES BAIRRO (cod_bairro) MATCH FULL
    ON UPDATE CASCADE ON DELETE CASCADE;