SELECT TRAT.COD_TRATAMENTO AS "Número do tratamento", PAC.NOME_PACIENTE AS "Paciente", 
(PAC.PESO/(PAC.ALTURA*PAC.ALTURA)) AS "IMC do paciente", DATE_PART('YEAR',(AGE(CURRENT_DATE,DATA_NASCIMENTO))) AS "Idade do paciente",
PAC.DATA_NASCIMENTO, RUA.RUA,BAIRRO.BAIRRO, ENDE.NUM_RESIDENCIA AS "Número da residência", 
ENDE.NUM_COMPLEMENTO AS "Número do complemento", CID.CIDADE, EST.ESTADO, INDISP.INDISPOSICAO AS "Tratamento", 
CD_MED.MEDICAMENTO, MEDICO.NOME_MEDICO AS "Nome do médico", CD_ESPEC.ESPECIALIDADE AS "Especialidade do médico",
TRAT.INI_TRAT AS "Inicio do tratamento", TRAT.FIM_TRAT AS "Fim do tratamento", 
HOSP.HOSPITAL FROM TRATAMENTO TRAT INNER JOIN PACIENTE PAC ON (TRAT.COD_PACIENTE = PAC.COD_PACIENTE)
INNER JOIN ENDERECO ENDE ON (PAC.COD_END = ENDE.COD_END) INNER JOIN RUA ON (ENDE.COD_RUA = RUA.COD_RUA)
INNER JOIN BAIRRO ON (RUA.COD_BAIRRO = BAIRRO.COD_BAIRRO) INNER JOIN CIDADE CID ON (BAIRRO.COD_CIDADE = CID.COD_CIDADE)
INNER JOIN ESTADO EST ON (CID.COD_ESTADO = EST.COD_ESTADO) INNER JOIN INDISPOSICAO INDISP ON (TRAT.COD_INDISPOSICAO = INDISP.COD_INDISPOSICAO)
INNER JOIN MEDICAMENTO MED ON (TRAT.COD_TRATAMENTO = MED.COD_TRATAMENTO) INNER JOIN CAD_MEDICAMENTO CD_MED ON (MED.COD_MEDICAMENTO = CD_MED.COD_MEDICAMENTO)
INNER JOIN MEDICO ON (TRAT.COD_MEDICO = MEDICO.COD_MEDICO) INNER JOIN ESPECIALIDADE ESPEC ON (MEDICO.COD_MEDICO = ESPEC.COD_MEDICO)
INNER JOIN CAD_ESPECIALIDADE CD_ESPEC ON (ESPEC.COD_ESPECIALIDADE = CD_ESPEC.COD_ESPECIALIDADE) INNER JOIN HOSPITAL HOSP ON (TRAT.COD_HOSPITAL = HOSP.COD_HOSPITAL)
GROUP BY PAC.COD_PACIENTE,TRAT.COD_TRATAMENTO,ENDE.COD_END,RUA.COD_RUA,BAIRRO.COD_BAIRRO,CID.COD_CIDADE,EST.COD_ESTADO,
MEDICO.COD_MEDICO,INDISP.COD_INDISPOSICAO,HOSP.COD_HOSPITAL,CD_MED.COD_MEDICAMENTO,CD_ESPEC.COD_ESPECIALIDADE ORDER BY TRAT.COD_TRATAMENTO DESC;